### PR TITLE
Bug fix - authentication cannot be turned on unless the username is empty

### PR DESCRIPTION
**Pull request by JuliusSweetland**

### CODE REVIEW

**Comment by soygul** [comment]
Actually, just adding `!` before condition is enough:

```csharp
if (!string.IsNullOrEmpty(this.usernameTextBox.Text))
```

**Comment by JuliusSweetland** [comment]
true, but there's no validation feedback in the configuration tool so maybe it should just let whatever the user specifies through?

**Comment by soygul** [comment]
https://github.com/JuliusSweetland/NBug/blob/master/NBug.Configurator/SubmitPanels/Web/Mail.cs#L191

**Comment by JuliusSweetland** [comment]
The code makes sense - it the user specifies authentication, but has not supplied a username, then turn off authentication. The problem, in my opinion, is that there is no feedback of this change to the user apart from the output xml, which may be encrypted.

**Comment by soygul** [comment]
True that! We should better display an error message to user. Something like:

```csharp
// Warn user if authentication is enabled but no username supplied
if (string.IsNullOrEmpty(this.usernameTextBox.Text))
{
   MessageBox.Show("You can't leave username empty when SMTP authentication is enabled!");
   return null;
}
```

**Comment by soygul** [comment]
Merging this. Will add the error message also.

Realized that this weirdness never caused any issue because of the extra logic here: https://github.com/soygul/NBug/blob/master/NBug/Core/Submission/Web/Mail.cs#L126

If username is supplied at least, useAuth=true anway.

**Pull request merged**
