### PR TITLE
allow to specify the share mode to use for AdditionalReportFiles

### PR DESCRIPTION
**Pull request by lelmarir**
Hi,

this is to allow to specify the share mode to use for additional files, and thus allow to add locked files like the log4net one:

NBug.Settings.AdditionalReportFiles.Add(((log4net.Appender.FileAppender)appender).File + ";share=ReadWrite");

otherwise, widouth this FileShare.Read will be used and the stream creation fails

### CODE REVIEW

**Comment by soygul** [comment]
What you're doing is right according to: http://stackoverflow.com/questions/3560651/whats-the-least-invasive-way-to-read-a-locked-file-in-c-sharp-perhaps-in-unsaf

However we can always open all files in `FileShare.ReadWrite` to simplify things. Passing `";share=ReadWrite"` seems like an unnecessary compilation. Can you test form me if always using `AddFile(..., FileShare.ReadWrite)` works without side effects? I don't have Windows at the moment.

**Comment by lelmarir** [comment]
Always using FileShare.ReadWrite was my first solution, but it does not feel right.
Some times you may need to ensure that the file is not opened by someone else (to ensure the consistency. I'm thinking of a db file or something like) and other time it is not needed.

We can think what should be the default share mode, but it might be useful to be able to use a different one for a specific file.

And this syntax could be used also for other things, for examle:

NBug.Settings.AdditionalReportFiles.Add("mylogfile.log" + ";tail=1000"); to only store the last 1000 lines of the log file

**Comment by soygul** [comment]
Well, if the file is opened by someone else, then it won't be included in the report because it can't be read anyhow (as in your case). I think including at least partially consistent file is better than never including it.

**Comment by lelmarir** [comment]
Might be, but i see this as the first step to a more comprehensive feature.

As said before, this syntax could support some file transformations before including them in the zip.

But, talking about the "share option", you can't know if partially consistent file is always better than not having it.
If the file at issue might be locked at runtime (not always as in my case), it will not get included and you know it was locked and, if included, it would not have been consistent.
Maybe we can also add some info to the report telling why it was not included, or support a fallback:

NBug.Settings.AdditionalReportFiles.Add("mylogfile.log" + ";share=None,ReadWrite");

this would tell NBug to first try to lock on the file, and if fail, read it anyway (logging the failure it in the report)

**Comment by soygul** [comment]
Ok fair enough. Attached string parameters are very error prone. Following fits the bill better:

```csharp
// NBug/Settings.cs
public static class Settings
{
  ...

  /// <summary>
  /// Gets or sets a list of additional files to be added to the report zip.
  /// </summary>
  public static List<AdditionalFile> AdditionalReportFiles { get; set; }

  public AdditionalFile
  {
    /// <summary>
    /// Gets or sets a the file path. The files can use * or ? in the same way as DOS modifiers.
    /// </summary>
    public string Path { get; set; }

    /// <summary>
    /// Gets or sets the the kind of access other processes can have access to the file white it's being zipped for the report. Defaults to FileShare.Read but other files might require FileShare.ReadWrite (i.e. log4net log files that are constantly open and can only be access with FileShare.ReadWrite).
    /// </summary>
    public FileShare FileShare { get; set; }
  }

  ...
}
```

**Comment by lelmarir** [comment]
like it,
i'll work on

**Comment by lelmarir** [comment]
Here it is, 
and it's also backward compatible. You can still write something like

NBug.Settings.AdditionalReportFiles.Add("myfile.log");

but i get some warnings "Type of '...' is not CLS-compliant".
I don't really know if this is important or if i can solve it in some way
(i'm a java programmer and some aspects of c# are still quite murky)

**Pull request closed without merging**
