### PR TITLE
Dispatcher runs till finish

### PR DESCRIPTION
**Pull request by schoetbi**
Here again without the formatting changes.
Thanks,
Tobias

### CODE REVIEW

**Comment by soygul** [comment]
Just reviewed it and now I get your objective. Current behavior (30 seconds wait before sending reports, and pausing if app exist) is the intended behavior (to mimic google-breakpad) and the entire library is designed around this behavior. Reasoning is well explained in the quickstart post and the configurator tool, so closing this.

**Comment by soygul** [comment]
If you want forced bug report sending, maintain your own fork but beware that it might break stuff so do some testing.

**Comment by schoetbi** [comment]
Yes, I need the immediate bug report sending, since after the application crahed the nrmal behaviour of our users is, that they call for help. And then it is very handy to have the bugreport beforehand.

So it seems, that I need to keep my fork.

Thanks for checking the changes so quickliy.

Regards,
Tobias

**Comment by soygul** [comment]
np, good luck!

**Pull request closed without merging**
