### PR TITLE
Updates Dependencies (Ready to Merge)

### PR DESCRIPTION
**Pull request by CDAGaming**
Sorry in Advance if any Duplicate Commits come in because of merging with this branch 👍

### CODE REVIEW

**Comment by CDAGaming** [comment]
XUnit Deps may have some issues, but ill try to migrate them over within a few days

**Comment by CDAGaming** [comment]
Forgot to mark as ready

**Comment by soygul** [comment]
As far as I know, changing `TargetFrameworkVersion` and `ToolsVersion` to latest will force people  to have latest .net framework and visual studio versions. Don't think that is appropriate.

**Comment by CDAGaming** [comment]
.Net 4.5.2 was the minimum requirement for some of the Dependency Updates. The toolsversion however, was from an auto upgrade on visual studios end, which I can undo manually to maintain compatibility in that area @soygul

**Comment by soygul** [comment]
I don't think forcing latest .net version for the entire lib just to update azure stuff is appropriate. This lib works fine with mono too. It won't the case any more if I merge this. Other parts of the PR is good though (editor config, minor changes). You can make smaller PRs for them if you want to.

**Comment by CDAGaming** [comment]
Ok, I'll do it when i have some time

**Pull request closed without merging**
